baseurl                  = "https://outlier-redemption.netlify.app/"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
defaultContentLanguageInSubdir = true
isMultilingual           = false
title                    = "outlier-redemption"
theme = "hugo-theme-sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "main"                           # What to call the home page link
    footerText           = "outlier-redemption."

# Metadata for Open Graph and Twitter
    description          = "This site is usually about giving (trashy) insights into (trashy) data. Nevertheless, it's sometimes about random facts coming from totally meaningful data."               # Max 160 characters show in search results
    images               = ["card-or.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "outlier-redemption"
    # rss                = ""

[params.videoBackground]
    overlay = "#272822" # optional

[languages]
  [languages.en]
    title = "outlier-redemption"
    contentDir = "content/english"
    weight = 1
    [[languages.en.params.mainMenu]]
      link = "posts"
      text = "stories"
    [[languages.en.params.mainMenu]]
      link = "https://tinyletter.com/outlier-redemption"
      text = "subscribe"
    [[languages.en.params.mainMenu]]
      link = "about"
      text = "about outlier-redemption"
  [languages.es]
    title = "outlier-redemption"
    contentDir = "content/spanish"
    weight = 2
    [[languages.es.params.mainMenu]]
      link = "posts"
      text = "historias"
    [[languages.es.params.mainMenu]]
      link = "https://tinyletter.com/violetrzn"
      text = "suscribite"
    [[languages.es.params.mainMenu]]
      link = "about"
      text = "sobre outlier-redemption"

#[[params.mainMenu]]
#    link = "posts"
#    text = "posts"

#[[params.mainMenu]]
#    link = "recommendations"
#    text = "advocacy"

#[[params.mainMenu]]
#    link = "about"
#    text = "about data-falopa"

[imaging]
    quality = 75